---
layout: page
title: 데이터 과학
subtitle: 그림을 파일에 저장
output:
  html_document: 
    keep_md: yes
  pdf_document:
    latex_engine: xelatex
mainfont: NanumGothic
---

```{r  include = FALSE}
source("tools/chunk-options.R")
knitr::opts_chunk$set(error = TRUE)
```

시간을 들여 작성한 시각화 산출물이 R 마크다운 문서 같은 동적문서 내부에만 존재하는 것으로 
항상 적절하거나 충분하지는 않다.
다양한 환경설정을 사용해서 다음 후속작업에 사용될 파일에 작업한 그림을 저장하는 방법을 익힐 필요가 있다.

시각화 산출물을 개발하는 동안에, `RStudio Plots` 창 같은 화면장치를 뿌려지는 그림을 보고 즉각적인 피드백을 받는다.
만족할만큼 작업이 완성되면 그림을 생성하는데 사용된 모든 명령어를 R 스크립트에 저장했는지 확실히 한다.
*모든 것*을 확인한다: 데이터 가져오기부터, 필요한 데이터 조작작업, 그래프 그리는 제도까지.

그림을 파일에 어떻게 저장할까요?

### 마우스에서 떨어져라 [^viz-save-plot]  

[^viz-save-plot]: [Writing figures to file](https://stat545-ubc.github.io/block017_write-figure-to-file.html)

마우스를 사용하는 작업 프로세스 유혹에 절대로 *굴복하지 마라*. 처음에는 마우스 사용이 편하다고 생각되지만,
곧 후회할 것이다. 이유는 마우스를 사용하게 되면 소스코드와 최종 그림 제품에 연결되는 링크가 없어진다.
다른 색상조합 혹은 종횡비, 그래픽장치로 그림을 재생성하고자 할 때, 적절한 소스코드를 까서 알아내야 된다.
이런 곤란한 상황을 타개하려면 아래 방법 중 하나를 사용한다.

### 좋은 명칭이 매우 중요하다.

그림을 생성하는 소스코드를 파일에 저장하려면, 
그림 파일에 컴퓨터가 읽을 수 있고, 문서가 필요없을 정도로 기억하기 좋은 명칭으로 작성한다면,
나중에 코드로 되돌아갈 수 있는 미래를 열게 된다.

[좀비 프로젝트](http://imgur.com/ewmBeQG)가 다시 살아나고, 동료 작업자가 [18개월 전에 생성한 그림](https://twitter.com/JohnDCook/status/522377493417033728)을
제시하는 상황을 상정하자. `fig08_scatterplot-lifeExp-vs-year.pdf` 파일을 평활회귀선을 넣은 TIFF 형식으로 다시 만들 수 있을까?

파일명을 통해 파일을 생성하는데 동원된 코드를 찾는데 도움이 되는 몇가지 속성을 넣을 수 있다:

- **인간-가독성**: 산점도와 더불어 중요한 변수가 어떤 것인지 알게 되는 것이 도움이 된다. 개인 고고학 발굴에 이런 정보가 중요한 맥락을 짚어준다.
- **구체성**: 그림파일 명칭이 얼마나 구체적이고 기술적인지 주목한다; `fig08.pdf` 혹은 `scatterplot.pdf` 같은 일반적인 
  파일명으로 끝나면 안된다. 파일명을 적어도 다수 유일무이한 특성이 갖도록 하는데,
  이렇게 하면 파일명 일부 혹은 전부가 담긴 파일을 검색하는데 도움이 된다.
- **컴퓨터-가독성**: 구체적 명칭 혹은 특정 문자열이 담긴 파일을 하드디스크에서 검색하는 기능을 최신 운영체제에서 제공한다.
  파일명에 공백, 구두점, 기타 이상한 것이 담겨있지 않게 되면, 파일 검색이 더 쉬워진다. 관례로 사용되는 확장자를 사용하게 되면,
  `.R` 혹은 `.Rmd`로 끝나는 파일로 검색범위를 좁힐 수 있다.

이 모든 선례를 참조하면 필요한 R코드를 겨냥해서 찾아내는데 도움이 된다.
이를 통해 코드를 변경하고, 재실행하고, 재사용할 수 있다.

### 그래픽 장치

    


























